version: '3'

services:

  database:
    build: ./database
    image: my-mongo
    ports:
      - "27017:27017"
    networks:
      - frontend
      - backend

  pres_node1:
    build: ./presentation/web/
    ports:
      - "8081:80"
    environment:
      - DATABASE_HOST=db
    networks:
      - frontend

  pres_node2:
    build: ./presentation/web/
    ports:
      - "8082:80"
    environment:
      - DATABASE_HOST=db
    networks:
      - frontend

  pres_node3:
    build: ./presentation/web/
    ports:
      - "8083:80"
    environment:
      - DATABASE_HOST=db
    networks:
      - frontend    

  presentation_loadbalancer:
    build: ./presentation/loadbalancer/
    ports:
      - "80:80"
    environment:
      - DATABASE_HOST=db
    depends_on:
      - pres_node1
      - pres_node2
      - pres_node3
    networks:
      - frontend
      - backend

  business_node1:
    build: ./business_logic/backend/
    ports:
      - "9081:80"
    environment:
      - DATABASE_HOST=db
    networks:
      - backend

  business_node2:
    build: ./business_logic/backend/
    ports:
      - "9082:80"
    environment:
      - DATABASE_HOST=db
    networks:
      - backend

  business_node3:
    build: ./business_logic/backend/
    ports:
      - "9083:80"
    environment:
      - DATABASE_HOST=db
    networks:
      - backend

  business_loadbalancer:
    build: ./business_logic/loadbalancer/
    ports:
      - "3000:80"
    environment:
      - DATABASE_HOST=db
    depends_on:
      - business_node1
      - business_node2
      - business_node3
    networks:
      - backend
      - frontend

networks:
  frontend:
  backend:
